version: '3'
services:
  python_env:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-python
    container_name: python_env
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    #Developer use    
    volumes:
      #- ./web:/app/
      - ./work_project:/app/
    #command:
      #- app.py
  jupyter:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "2234:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      #- ./jupyter:/home/jovyan/work
      - ./work_project:/home/jovyan/work
