FROM python:3.7

# add project
#ADD ./work_project /app #since we have to voluumes
WORKDIR /app

# install flask
RUN pip install --upgrade pip
RUN pip install --upgrade pip
RUN pip install bs4 
RUN pip install requests
RUN pip install selenium 
RUN pip install pandas 
RUN pip install numpy 
RUN pip install time 
RUN pip install random 
RUN pip install os
RUN pip install datetime
RUN pip install json 
RUN pip install pymysql

# run flask
#ENTRYPOINT ["python"]
#CMD ["test_app.py"]

#RUN /bin/bash -c 'python test_app.py'

# run flask
ENTRYPOINT ["python"]#like son process
#CMD ["python app.py"]